name: fary_tales
description: A bedtime stories app for children
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  lottie: ^3.0.0
  shared_preferences: ^2.2.2
  flutter_vibrate: ^1.3.0
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Add assets here
  assets:
    - assets/data/stories.json
    - assets/sounds/
    - assets/animations/
